### ISSUE TITLE
Won't open 

### ISSUE THREAD

**Issue by LordSith77** [Xerren09/Sons-Of-The-Forest-Companion-Rescue-Tool#1]
If the game is running, I get the message about exiting the game. Once the game is exited, the tool won't load at all.

**Comment by Xerren09** [comment]
Sorry for the delay, I somehow missed this. Are you trying to edit a singleplayer or multiplayer save? Singleplayer *should* work as long as you have a save, but if you are editing a multiplayer save, you need to be the host otherwise you don't have the necessary files.

**Comment by LordSith77** [comment]
Neither. The program won't open at all. I even tried to open it as admin and nothing. 
The program itself won't open.

**Comment by Xerren09** [comment]
It most likely means there are no game save files to interact with.

Just for diagnostics, go to `%userprofile%\appdata\locallow\Endnight\SonsOfTheForest\Saves\`, step into the directory that's just a bunch of numbers, and it should have a `Singleplayer` and / or `Multiplayer` directories. 
If neither exists (or empty, or you only have `MultiplayerClient`), it's something I didn't account for and crashes the program immediately.

Hopefully this is the case, and then I can fix it tonight.

**Comment by LordSith77** [comment]
I have SinglePlayer, Multiplayer and MultiplayerClient.
![image](https://github.com/Xerren09/Sons-Of-The-Forest-Companion-Rescue-Tool/assets/26206442/704884df-1168-4447-9600-3bf55fc88601)

And there are save files in each folder.
Could it be that they changed the way save files are saved? Now the whole thing is inside a zip file.

**Comment by Xerren09** [comment]
Ooh that's weird. I haven't played since ~early early-access, so I didn't know they changed it. Will take a look to see if anything else changed but if it's just a zip, I can fix this up very soon, thanks a lot for pointing it out! :)

**Comment by LordSith77** [comment]
Yeah, I've noticed a lot of "tutorials" on how to get Kelvin back was all outdated, and very few talk about the files being zipped up now. Hopefully your program will be able to work with the new format. :-)

**Comment by Xerren09** [comment]
Fixed it over the weekend, and now it works with the new saves!
You can grab the new version from [releases](https://github.com/Xerren09/Sons-Of-The-Forest-Companion-Rescue-Tool/releases/tag/v2.0.0). If there is anything wrong, do let me know, and I'll take a look :)

**Comment by LordSith77** [comment]
Awesome! Works perfectly now. Thank you for all your hard work.
